#ifndef HTTPSTATUS_HPP
# define HTTPSTATUS_HPP

enum HttpStatus
{
	HTTP_STATUS_NONE = 0,
	HTTP_STATUS_OK = 200,
	HTTP_STATUS_BAD_REQUEST = 400,
	HTTP_STATUS_FORBIDDEN = 403,
	HTTP_STATUS_CONTENT_TOO_LARGE = 413,
	HTTP_STATUS_URI_TOO_LONG = 414,
	HTTP_STATUS_REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
	HTTP_STATUS_NOT_IMPLEMENTED = 501,
	HTTP_STATUS_HTTP_VERSION_NOT_SUPPORTED = 505
};

#endif
